// Fastify app composition. Pulls everything together; main.ts handles
// listen + signal handling.

import fastifyCookie from "@fastify/cookie";
import fastifyStatic from "@fastify/static";
import Fastify, { type FastifyInstance } from "fastify";

import type { Config } from "./config.js";
import { openDatabase, type DB } from "./db.js";
import { registerIdentity } from "./identity.js";
import { registerAdmin } from "./routes/admin.js";
import { registerHealth } from "./routes/health.js";
import { registerMe } from "./routes/me.js";
import { registerPosts } from "./routes/posts.js";
import { registerUploads } from "./routes/uploads.js";

export interface BuildResult {
  app: FastifyInstance;
  db: DB;
}

export async function buildApp(cfg: Config): Promise<BuildResult> {
  const db = openDatabase(cfg.dataDir);

  const app = Fastify({
    logger: {
      level: cfg.logLevel,
      // request.id is generated by fastify; we surface it in logs to
      // correlate auth header weirdness with a specific hit.
      redact: ["req.headers.cookie", "req.headers.authorization"],
    },
    // Trust the upstream Caddy. fastify uses this to derive request.ip from
    // X-Forwarded-For. Identity middleware does its own CIDR check on the
    // resulting value, so even if a malicious header is set the peer check
    // catches it.
    trustProxy: true,
    bodyLimit: 1 * 1024 * 1024, // JSON bodies only; uploads use multipart.
  });

  // Plugins. (auth-svc on the potato already does per-IP rate limiting at
  // the gate, so we don't double up here.)
  await app.register(fastifyCookie);

  // Identity hook FIRST — every other route assumes request.identity is set
  // for /api/*.
  registerIdentity(app, cfg);

  // API routes.
  registerHealth(app);
  registerMe(app, cfg, db);
  registerPosts(app, db);
  await registerUploads(app, cfg, db);
  registerAdmin(app, cfg, db);

  // Static SPA. Served from /app/web/dist in production. Any request that
  // didn't match /api/* falls through here. setNotFoundHandler below catches
  // SPA deep links and returns index.html.
  await app.register(fastifyStatic, {
    root: cfg.webRoot,
    prefix: "/",
    cacheControl: true,
    maxAge: "1h",
    // Don't serve index automatically — we want explicit index.html for
    // deep-link fallthrough.
    index: false,
    decorateReply: true,
  });

  app.get("/", async (_request, reply) => {
    return reply.sendFile("index.html");
  });

  app.setNotFoundHandler((request, reply) => {
    // Anything under /api/* that didn't match a route gets a real 404.
    if (request.url.startsWith("/api/")) {
      reply.code(404).send({ error: "not_found" });
      return;
    }
    // SPA fallback: send index.html so client-side routing takes over.
    reply.type("text/html").sendFile("index.html");
  });

  // Generic error logging (no stack to client).
  app.setErrorHandler((err, request, reply) => {
    request.log.error({ err }, "request errored");
    const status = err.statusCode && err.statusCode >= 400 ? err.statusCode : 500;
    reply.code(status).send({ error: err.code ?? "internal" });
  });

  app.log.info(
    {
      dataDir: cfg.dataDir,
      uploadsDir: cfg.uploadsDir,
      webRoot: cfg.webRoot,
      ownerConfigured: cfg.ownerTokenId.length > 0,
      trustedCidrs: cfg.trustedCidrs.map((c) => c.raw),
      perUserQuotaBytes: cfg.perUserQuotaBytes,
    },
    "pi4-web ready",
  );

  return { app, db };
}
